version: '3'

services:
  frontend:
    image: shoeb2144/react:latest
    ports:
      - "80:3000"

  backend:
    image: shoeb2144/nodejs:latest
    ports:
      - "3000:5001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_dp:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo_dp: {}
